version: "3"
services:
  sut:
    build: .
    shm_size: 256m
    volumes:
      - ./result:/work/result
      - ./test/spec:/work/spec/test:ro
      - ./test/steps:/work/spec/steps:ro
      - ./test/features:/work/spec/features:ro
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
