version: "3"
services:
  e2e:
    image: ${APP_IMAGE:-localhost:15000/testing-image}
    shm_size: 256m
    volumes:
      - ../_build/e2e:/work/result
      - ./test/spec:/work/spec/test:ro
      - ./test/steps:/work/spec/steps:ro
      - ./test/features:/work/spec/features:ro
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine

